# Brownie configuration file
# https://eth-brownie.readthedocs.io/en/stable/config.html
pytest:
    # these settings replace the defaults when running pytest
    gas_limit: 6721975
    default_contract_owner: false
    reverting_tx_gas_limit: 6721975
    revert_traceback: true
compiler:
    evm_version: null
    #minify_source: false
    solc:
        version: null
        optimize: true
        runs: 200
colors:
    key:
    value: bright blue
    callable: bright cyan
    module: bright blue
    contract: bright magenta
    contract_method: bright magenta
    string: bright magenta
    dull: dark white
    error: bright red
    success: bright green
    pending: bright yellow
